src/CERP/SiteBundle/Form/ListRouteFormType.php
<?php 
namespace CERP\SiteBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;


class ListRouteFormType extends AbstractType
{
    private $oContainer;
    private $oListRoutes;

    public function __construct($oContainer)
    {
        $this->oContainer = $oContainer;

        $oRoutes = $oContainer->get('router');
        $oRoutes = $oRoutes->getRouteCollection()->all();

        $aRoutes = [];

        $oGlobalFunctions = $oContainer->get('globalfunctions');
        //if ( $oGlobalFunctions->strpos_arr($iKey, $this->oContainer->getParameter('a2lix_translation_form.locales'), "__RG") !== false )    

        $sDefaultLanguage = $this->oContainer->getParameter('locale');
        $sDefaultLanguagePrefixRoute = $sDefaultLanguage . "__RG__AS";

        foreach ($oRoutes as $iKey => $sValue) 
        {
            if ( strpos($iKey, $sDefaultLanguagePrefixRoute) !== false )    
            $aRoutes[substr($iKey, count($sDefaultLanguage) + 1)] = $sValue->getPath();
        }

        $this->oListRoutes = $aRoutes;

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'choices' => $this->oListRoutes
        ));
    }

    

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'list_route_form';
    }
}


 ?>

src/CERP/SiteBundle/Resources/views/CRUD/edit_orm_one_association_script.html.twig
{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}


{#

This code manage the one-to-many association field popup

#}

{% autoescape false %}

<!-- edit one association -->

<script type="text/javascript">

    // handle the add link
    var field_add_{{ id }} = function(event) {

        event.preventDefault();
        event.stopPropagation();

        var form = jQuery(this).closest('form');

        // the ajax post
        jQuery(form).ajaxSubmit({
            url: '{{ path('sonata_admin_append_form_element', {
                'code':      sonata_admin.admin.root.code,
                'elementId': id,
                'objectId':  sonata_admin.admin.root.id(sonata_admin.admin.root.subject),
                'uniqid':    sonata_admin.admin.root.uniqid,
                'subclass': app.request.query.get('subclass'),
            } + sonata_admin.field_description.getOption('link_parameters', {})) }}',
            type: "POST",
            dataType: 'html',
            data: { _xml_http_request: true },
            success: function(html) {
                if (!html.length) {
                    return;
                }

                jQuery('#field_container_{{ id }}').replaceWith(html); // replace the html

                Admin.shared_setup(jQuery('#field_container_{{ id }}'));

                if(jQuery('input[type="file"]', form).length > 0) {
                    jQuery(form).attr('enctype', 'multipart/form-data');
                    jQuery(form).attr('encoding', 'multipart/form-data');
                }
                jQuery('#sonata-ba-field-container-{{ id }}').trigger('sonata.add_element');
                jQuery('#field_container_{{ id }}').trigger('sonata.add_element');


            }
        });

        return false;
    };

    var field_widget_{{ id }} = false;

    // this function initialize the popup
    // this can be only done this way has popup can be cascaded
    function start_field_retrieve_{{ id }}(link) {

        link.onclick = null;

        // initialize component
        field_widget_{{ id }} = jQuery("#field_widget_{{ id }}");

        // add the jQuery event to the a element
        jQuery(link)
            .click(field_add_{{ id }})
            .trigger('click')
        ;

        return false;
    }
</script>

<!-- / edit one association -->

{% endautoescape %}

src/CERP/SiteBundle/Resources/views/CRUD/list_orm_many_to_many.html.twig
{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}

{% extends admin.getTemplate('base_list_field') %}
{% block field %}
    {% if value|length > 4 %}
        <a href="#" title="Number of associations element" class="preventDefault show-associations first-count-associations">{{ value|length }}<span> (show)</span></a>
    <span class="hide-associations association-list">
    {% endif %}
    {% if field_description.hasassociationadmin and field_description.associationadmin.hasRoute('edit') %}
        {% for element in value%}
            {%- if field_description.associationadmin.isGranted('EDIT', value) -%}
                *{{ block('relation_link') }}*
            {%- else -%}
                *{{ block('relation_value') }}*
            {%- endif -%}
            {% if not loop.last %}
                 </br>
            {% else %} 
                {% if value|length > 4 %}
                    <a href="#" title="Number of associations element" class="preventDefault show-associations last-count-associations">{{ value|length }}<span> (hide)</span></a> 
                {% endif %}
            {% endif %}
        {% endfor %}
    {% else %}
        {% for element in value%}
            *{{ block('relation_value') }}*
            {% if not loop.last %}
                </br> 
            {% else %} 
                {% if value|length > 4 %}
                    <a href="#" title="Number of associations element" class="preventDefault show-associations last-count-associations">{{ value|length }}<span> (hide)</span></a> 
                {% endif %}
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if value|length > 4 %}</span>{% endif %}
{% endblock %}
{%- block relation_link -%}
    <a href="{{ field_description.associationadmin.generateObjectUrl(field_description.options.route.name, element, field_description.options.route.parameters) }}">{{ element|render_relation_element(field_description) }}</a>
{%- endblock -%}

{%- block relation_value -%}
    {{ element|render_relation_element(field_description) }}
{%- endblock -%}